# Generated by Django 2.0.1 on 2018-01-10 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180110_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
