# Generated by Django 2.0.1 on 2018-01-11 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_articale_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
